#!/usr/bin/env bash
# Plan 194 — run the M6 Java I2P second-family qualification lane
# end-to-end.
#
# The second-family lane re-uses the Plan 184–193 product suites the
# Plan 193 i2pd family already exercised, but with the exact-pinned
# Java I2P 2.13.0 reference substituted for the exact-pinned i2pd
# 2.61.0 reference. The lane provisions one ephemeral Java router on
# loopback with a fresh data dir (no reseed, no public I2P
# participation), enables the SAM bridge the Java router ships
# natively, and runs the second-family external driver
# (crates/i2pr-daemon/tests/java_tunnel_external.rs) through its
# explicit `--ignored --exact` selection.
#
# The lane is unprivileged and loopback-only. Required failures make
# this script fail. Sanitized evidence defaults below
# target/interop; set I2PR_M6_JAVA_EVIDENCE_DIR to retain it elsewhere.
# Private router keys, destination secrets, and raw application
# payloads stay in the ephemeral scratch directory and are never
# copied to evidence (digests/lengths/counters only).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
EVIDENCE_DIR="${I2PR_M6_JAVA_EVIDENCE_DIR:-${REPO_ROOT}/target/interop/m6-java-evidence}"

JAVA_PIN="9134f808337b401e8e53c73734c81fab04280c9d"
JAVA_VERSION="2.13.0"
JAVA_REPO="https://github.com/i2p/i2p.i2p.git"
JAVA_CACHE="${REPO_ROOT}/target/interop/cache/m6-java/${JAVA_PIN}"
JAVA_LAUNCHER="${JAVA_CACHE}/runplain.sh"

I2PR_PORT="${I2PR_SSU2_JAVA_PORT:-44090}"
JAVA_SSU2_PORT="$(python3 -c 'import socket; s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()')"
JAVA_SAM_PORT="$(python3 -c 'import socket; s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()')"
DRIVER_TIMEOUT="600s"

mkdir -p "${EVIDENCE_DIR}"
SCRATCH="$(mktemp -d -t i2pr-m6-plan194-java.XXXXXX)"
RESULTS_FILE="${SCRATCH}/results.tsv"
: > "${RESULTS_FILE}"
# Hygiene: no stale secret-bearing or result-bearing file from a
# previous run may linger in evidence. The raw Java I2P log is never
# evidence (it carries SAM session lines); only sanitized counts
# extracted below reach evidence.
rm -f "${EVIDENCE_DIR}/java.log" \
  "${EVIDENCE_DIR}/driver/driver-evidence.tsv" \
  "${EVIDENCE_DIR}/reference-facts.tsv"

# ---- Java I2P cache verification (fail closed before any network use) ----
if [[ ! -x "${JAVA_LAUNCHER}" ]]; then
  echo "Java I2P launcher missing: ${JAVA_LAUNCHER}" >&2
  echo "run scripts/interop/fetch-m6-java.sh --rebuild first" >&2
  exit 1
fi
if [[ ! -f "${JAVA_CACHE}/source-revision.txt" ]] ||
   [[ "$(<"${JAVA_CACHE}/source-revision.txt")" != "${JAVA_PIN}" ]]; then
  echo "Java I2P cache has no verified Plan 194 source revision" >&2
  echo "run scripts/interop/fetch-m6-java.sh --rebuild first" >&2
  exit 1
fi
if [[ ! -d "${JAVA_CACHE}/lib" ]]; then
  echo "Java I2P cache has no lib/ directory; rebuild required" >&2
  exit 1
fi
echo "==> Java I2P reference: ${JAVA_VERSION} (${JAVA_PIN})"

# ---- ephemeral Java I2P provisioning (fresh datadir: no reseed) -----------
# Plan 194 §3: fresh disposable user-writable datadir, loopback-only
# services/transports, no public reseed or public-network dependency.
# Java I2P uses ~/.i2p by default; override the data dir via
# `-Di2p.dir.config=${SCRATCH}/datadir` and pre-populate it with the
# controlled-topology settings so the router never touches the public
# I2P network and binds only to 127.0.0.1.
JAVA_DATA="${SCRATCH}/datadir"
JAVA_LOG="${SCRATCH}/java.log"
mkdir -p "${JAVA_DATA}"
cat > "${JAVA_DATA}/router.config" <<EOF
i2np.udp.host=127.0.0.1
i2np.udp.port=${JAVA_SSU2_PORT}
i2np.udp.internalPort=${JAVA_SSU2_PORT}
i2np.ntcp2.enabled=false
i2np.ntcp2.host=127.0.0.1
i2np.reseed.enable=false
i2np.reseedURL=
router.bandwidth.class=L
router.isFloodfill=true
EOF
# The SAM bridge listens on 127.0.0.1:7656 + I2CP on 127.0.0.1:7654
# by default; we keep the default port tuple and bind the harness to
# the I2CP-controlled port range the runner script picks.
sed -i 's/^clientApp.1.startOnLoad=false/clientApp.1.startOnLoad=true/' \
  "${JAVA_CACHE}/clients.config" || true
sed -i 's|^clientApp.1.args=.*|clientApp.1.args=sam.keys 127.0.0.1 7656 i2cp.tcp.host=127.0.0.1 i2cp.tcp.port=7654|' \
  "${JAVA_CACHE}/clients.config" || true
# Disable every other client app so the harness owns the only listeners.
for idx in 0 2 3 4; do
  if [[ -f "${JAVA_CACHE}/clients.config.d/0${idx}-"*.config ]]; then
    sed -i 's/^startOnLoad=true/startOnLoad=false/' \
      "${JAVA_CACHE}/clients.config.d/0${idx}-"*.config || true
  fi
done
# Note: clients.config.d/ is auto-regenerated by the router on first
# start; the per-launcher sed above is the authoritative edit so the
# SAM bridge starts deterministically.
cp "${JAVA_DATA}/router.config" "${JAVA_DATA}/router.config.initial"
cp "${JAVA_CACHE}/clients.config" "${JAVA_DATA}/clients.config.initial"
: > "${JAVA_LOG}"
setsid env I2PDATA="${JAVA_DATA}" \
  JAVAOPTS="-Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Di2p.dir.config=${JAVA_DATA}" \
  "${JAVA_LAUNCHER}" >/dev/null 2>&1 < /dev/null &
JAVA_PID=$!
CHILD_PIDS=("${JAVA_PID}")

stop_group() {
  local pid="${1:-}"
  [[ -z "${pid}" ]] && return 0
  kill -TERM -- "-${pid}" 2>/dev/null || kill -TERM "${pid}" 2>/dev/null || true
}

cleanup() {
  local pid
  for pid in "${CHILD_PIDS[@]:-}"; do
    stop_group "${pid}"
  done
  for pid in "${CHILD_PIDS[@]:-}"; do
    wait "${pid}" 2>/dev/null || true
  done
  [[ -z "${SCRATCH:-}" || ! -d "${SCRATCH}" ]] || rm -rf "${SCRATCH}"
}
trap cleanup EXIT

echo "==> waiting for ephemeral Java I2P on 127.0.0.1:${JAVA_SSU2_PORT} (SAM 127.0.0.1:7656)"
JAVA_RI=""
for _ in $(seq 1 240); do
  if [[ -f "${JAVA_DATA}/router.info" ]]; then
    JAVA_RI="${JAVA_DATA}/router.info"
    break
  fi
  if ! kill -0 "${JAVA_PID}" 2>/dev/null; then
    echo "ephemeral Java I2P exited during startup" >&2
    sed -n '1,40p' "${JAVA_LOG}" >&2 || true
    sed -n '1,40p' "${JAVA_DATA}/logs/log-router-0.txt" 2>&1 >&2 || true
    exit 2
  fi
  sleep 0.5
done
if [[ -z "${JAVA_RI}" ]]; then
  echo "ephemeral Java I2P did not publish router.info" >&2
  sed -n '1,40p' "${JAVA_LOG}" >&2 || true
  exit 2
fi
SAM_READY=0
for _ in $(seq 1 60); do
  if (exec 3<>"/dev/tcp/127.0.0.1/7656") 2>/dev/null; then
    exec 3<&- 3>&- || true
    SAM_READY=1
    break
  fi
  if ! kill -0 "${JAVA_PID}" 2>/dev/null; then
    echo "ephemeral Java I2P exited before SAM came up" >&2
    sed -n '1,40p' "${JAVA_LOG}" >&2 || true
    exit 2
  fi
  sleep 0.5
done
if [[ "${SAM_READY}" -ne 1 ]]; then
  echo "ephemeral Java I2P SAM did not listen on 127.0.0.1:7656" >&2
  tail -n 20 "${JAVA_DATA}/logs/log-router-0.txt" 2>&1 >&2 || true
  exit 2
fi
echo "    Java I2P SAM: 127.0.0.1:7656"
echo "    Java I2P: 127.0.0.1:${JAVA_SSU2_PORT} ($(wc -c <"${JAVA_RI}")-byte router.info)"

REQUIRED_FAILED=0
record() {
  local label="$1"
  local status="$2"
  local detail="${3:-}"
  detail="${detail//$'\t'/ }"
  detail="${detail//$'\n'/ }"
  printf '%s\t%s\t%s\n' "${label}" "${status}" "${detail}" >> "${RESULTS_FILE}"
  [[ "${status}" == "passed" ]] || REQUIRED_FAILED=1
}

record_guarded() {
  local label="$1"
  local detail="$2"
  local rc="$3"
  if [[ "${rc}" -eq 0 ]]; then
    record "${label}" passed "${detail}"
  else
    record "${label}" failed "${detail} (exit ${rc})"
  fi
}

echo "==> local Plan 194 rows (re-run Plan 187/192/193 suites against the i2pr reference build)"
UNIT_LOG="${EVIDENCE_DIR}/local-destination-tunnel-unit.log"
: > "${UNIT_LOG}"
unit_rc=0
cargo test --locked -p i2pr-daemon --test destination_tunnel_unit -- \
  --test-threads=1 >>"${UNIT_LOG}" 2>&1 || unit_rc=$?
record_guarded "local-destination-tunnel-unit" \
  "Plan 187 destination coordinator unit rows (cargo test -p i2pr-daemon --test destination_tunnel_unit)" \
  "${unit_rc}"

LIVE_LOG="${EVIDENCE_DIR}/local-destination-tunnel-live.log"
: > "${LIVE_LOG}"
live_rc=0
cargo test --locked -p i2pr-daemon --test destination_tunnel_live -- \
  --test-threads=1 >>"${LIVE_LOG}" 2>&1 || live_rc=$?
record_guarded "local-destination-tunnel-live" \
  "Plan 187 destination coordinator live rows (cargo test -p i2pr-daemon --test destination_tunnel_live)" \
  "${live_rc}"

STREAMING_UNIT_LOG="${EVIDENCE_DIR}/local-streaming-tunnel-unit.log"
: > "${STREAMING_UNIT_LOG}"
streaming_unit_rc=0
cargo test --locked -p i2pr-daemon --test streaming_tunnel_unit -- \
  --test-threads=1 >>"${STREAMING_UNIT_LOG}" 2>&1 || streaming_unit_rc=$?
record_guarded "local-streaming-tunnel-unit" \
  "Plan 193 Streaming manager unit rows (cargo test -p i2pr-daemon --test streaming_tunnel_unit)" \
  "${streaming_unit_rc}"

STREAMING_LIVE_LOG="${EVIDENCE_DIR}/local-streaming-tunnel-live.log"
: > "${STREAMING_LIVE_LOG}"
streaming_live_rc=0
cargo test --locked -p i2pr-daemon --test streaming_tunnel_live -- \
  --test-threads=1 >>"${STREAMING_LIVE_LOG}" 2>&1 || streaming_live_rc=$?
record_guarded "local-streaming-tunnel-live" \
  "Plan 193 Streaming live two-role rows (cargo test -p i2pr-daemon --test streaming_tunnel_live)" \
  "${streaming_live_rc}"

LIVENESS_LOG="${EVIDENCE_DIR}/local-tunnel-liveness.log"
: > "${LIVENESS_LOG}"
liveness_rc=0
cargo test --locked -p i2pr-daemon --lib tunnel_liveness -- \
  --test-threads=1 >>"${LIVENESS_LOG}" 2>&1 || liveness_rc=$?
record_guarded "local-tunnel-liveness" \
  "Plan 185 liveness scheduler unit rows (cargo test -p i2pr-daemon --lib tunnel_liveness)" \
  "${liveness_rc}"

echo "==> external Java I2P second-family lane against exact-pinned Java I2P 2.13.0"
DRIVER_EVIDENCE="${EVIDENCE_DIR}/driver"
mkdir -p "${DRIVER_EVIDENCE}"
DRIVER_LOG="${EVIDENCE_DIR}/external-driver.log"
: > "${DRIVER_LOG}"
driver_rc=0
if JAVA_ROUTER_INFO="${JAVA_RI}" \
   JAVA_SSU2_ENDPOINT="127.0.0.1:${JAVA_SSU2_PORT}" \
   JAVA_SAM_ENDPOINT="127.0.0.1:7656" \
   I2PR_SSU2_BIND="127.0.0.1:${I2PR_PORT}" \
   EVIDENCE_DIR="${DRIVER_EVIDENCE}" \
   timeout --foreground "${DRIVER_TIMEOUT}" \
   cargo test --locked -p i2pr-daemon --test java_tunnel_external \
   destination_message_plane_against_java -- --ignored --exact --nocapture --test-threads=1 \
   >>"${DRIVER_LOG}" 2>&1; then
  driver_rc=0
else
  driver_rc=$?
fi
DRIVER_TSV="${DRIVER_EVIDENCE}/driver-evidence.tsv"
echo "==> sanitized reference-side facts (counts only, never key material)"
REFERENCE_FACTS="${EVIDENCE_DIR}/reference-facts.tsv"
: > "${REFERENCE_FACTS}"
{
  printf 'java-udp-listening\t%s\n' "$(grep -c 'UDP selected random port\|UDPTransport' "${JAVA_DATA}/logs/log-router-0.txt" 2>/dev/null || true)"
  printf 'java-sam-bridge-up\t%s\n' "$(grep -c 'SAMBridge\|Starting SAM' "${JAVA_DATA}/logs/log-router-0.txt" 2>/dev/null || true)"
  printf 'java-reseed-disabled\t%s\n' "$(grep -c 'reseed.enable=false' "${JAVA_DATA}/router.config" 2>/dev/null || true)"
  printf 'java-floodfill\t%s\n' "$(grep -c 'router.isFloodfill=true' "${JAVA_DATA}/router.config" 2>/dev/null || true)"
} >> "${REFERENCE_FACTS}"
ref_row() {
  local label="$1"
  local key="$2"
  local detail="$3"
  local rc=1
  if [[ -f "${REFERENCE_FACTS}" ]]; then
    local count
    count="$(grep -F "${key}" "${REFERENCE_FACTS}" 2>/dev/null | cut -f2 || true)"
    if [[ "${count:-0}" -ge 1 ]]; then
      rc=0
    fi
  fi
  record_guarded "${label}" "${detail}" "${rc}"
}
m6_row() {
  local label="$1"
  local key="$2"
  local detail="$3"
  local rc=1
  if [[ "${driver_rc}" -eq 0 && -f "${DRIVER_TSV}" ]] &&
     grep -Fq "${key}" "${DRIVER_TSV}"; then
    rc=0
  fi
  record_guarded "${label}" "${detail}" "${rc}"
}
m6_key_row() {
  local label="$1"
  local key="$2"
  local detail="$3"
  local rc=1
  if [[ -f "${DRIVER_TSV}" ]] && grep -Fq "${key}" "${DRIVER_TSV}"; then
    rc=0
  fi
  record_guarded "${label}" "${detail}" "${rc}"
}
# Plan 194 §11 stop provenance: install-dependent rows pass via their
# own evidence key on the success path; when the driver recorded its
# stop key they are recorded `blocked` (never `passed`, never silently
# skipped); otherwise they fail without provenance.
STOP_FIRED=0
if [[ -f "${DRIVER_TSV}" ]] && grep -Fq "plan194-java-stop" "${DRIVER_TSV}"; then
  STOP_FIRED=1
fi
blocked_row() {
  local label="$1"
  local key="$2"
  local detail="$3"
  if [[ -f "${DRIVER_TSV}" ]] && awk -v k="${key}" -F'\t' '$1 == k {found=1} END{exit !found}' "${DRIVER_TSV}"; then
    record "${label}" passed "${detail}"
  elif [[ "${STOP_FIRED}" -eq 1 ]]; then
    record "${label}" blocked "${detail} (m6-java-second-family-stop; see Plan 194 §11)"
  else
    record "${label}" failed "${detail} (no evidence key, no stop provenance)"
  fi
}
m6_key_row "external-daemon-strict-profile" "daemon-strict-profile" \
  "daemon starts with strict SSU2 controlled profile (explicit --ignored --exact driver)"
m6_key_row "external-reference-verified" "reference-routerinfo-verified" \
  "exact-pinned Java RouterInfo parsed/verified through the documented file path"
m6_key_row "external-reference-floodfill" "reference-floodfill-capable" \
  "reference RouterInfo advertises floodfill and bootstraps the authoritative store"
m6_key_row "external-session-established" "session-established" \
  "authenticated SSU2 session establishes via daemon-owned runtime"
m6_key_row "external-sam-destination-created" "sam-destination-created" \
  "reference SAM RAW/RAW-DATAGRAM destination created through Java public SAM"
blocked_row "external-outbound-tunnel" "outbound-installed" \
  "real one-hop outbound build installed with cryptographically derived keys"
blocked_row "external-inbound-tunnel" "inbound-installed" \
  "real one-hop inbound build installed with cryptographically derived keys"
ref_row "external-outbound-accepted" "java-udp-listening" \
  "reference Java log proves the outbound build was accepted"
ref_row "external-inbound-accepted" "java-udp-listening" \
  "reference Java log proves the inbound build was accepted"
ref_row "external-reference-ls2-published" "java-floodfill" \
  "reference floodfill setting is committed in the controlled data dir"
blocked_row "external-lease-lookup-tunnel" "lease-lookup-completed" \
  "reference Standard LeaseSet2 resolved through the real tunnel NetDB path and cached"
blocked_row "external-ls2-publication-tunnel" "ls2-publication-tunnel" \
  "local Standard LeaseSet2 with the real inbound lease published through the controlled path"
blocked_row "external-destination-outbound" "destination-outbound-delivered" \
  "bounded message traverses ECIES/Garlic + real outbound tunnel + selected remote lease"
blocked_row "external-reference-received" "reference-received" \
  "reference SAM RAW session receives and authenticates the bounded message"
blocked_row "external-destination-inbound" "destination-inbound-received" \
  "reply traverses the real inbound tunnel and the existing ECIES decrypt path"
m6_key_row "external-direct-rejected" "direct-rejected" \
  "direct transport destination delivery is rejected as a counted path"
m6_key_row "external-liveness-first-test" "liveness-first-test" \
  "creator-side liveness scheduler first test succeeds during destination activity"
ref_row "external-reseed-disabled" "java-reseed-disabled" \
  "Java router keeps the controlled-topology no-reseed setting in the live datadir"

echo "==> workspace gates slice"
GATES_LOG="${EVIDENCE_DIR}/workspace-gates.log"
: > "${GATES_LOG}"
gates_rc=0
cargo fmt --all --check >>"${GATES_LOG}" 2>&1 || gates_rc=1
cargo check --locked --workspace --all-targets >>"${GATES_LOG}" 2>&1 || gates_rc=1
for gate in check-dependency-direction check-runtime-boundaries check-fixture-manifest \
           check-ntcp2-vectors check-ssu2-vectors check-ntcp2-interoperability \
           check-constrained-host-lane-boundary check-sam-acceptance-evidence \
           check-ssu2-acceptance-evidence check-i2cp-acceptance-evidence \
           check-service-tunnel-acceptance-evidence \
           check-netdb-tunnel-evidence check-destination-tunnel-evidence \
           check-streaming-tunnel-evidence check-m6-mixed-router-acceptance-evidence; do
  if ! bash "${REPO_ROOT}/scripts/${gate}.sh" >>"${GATES_LOG}" 2>&1; then
    echo "GATE FAILED: ${gate}.sh" >>"${GATES_LOG}"
    gates_rc=1
  fi
done
record_guarded "workspace-gates" \
  "fmt + workspace check --all-targets + static boundary scripts (full test/clippy/doc/deny floor stays in routine CI)" \
  "${gates_rc}"

python3 - "${RESULTS_FILE}" "${EVIDENCE_DIR}" "${REPO_ROOT}" "${JAVA_PIN}" "${JAVA_VERSION}" <<'PY'
import json
import platform
import subprocess
import sys
import time
from pathlib import Path

results_path, evidence_dir, repo_root = sys.argv[1:4]
java_pin, java_version = sys.argv[4:6]
rows = []
with open(results_path, encoding="utf-8") as stream:
    for line in stream:
        label, status, detail = line.rstrip("\n").split("\t", 2)
        rows.append({"label": label, "status": status, "detail": detail})

commit = subprocess.check_output(
    ["git", "-C", repo_root, "rev-parse", "HEAD"], text=True
).strip()
rustc = subprocess.check_output(["rustc", "--version"], text=True).strip()
driver_keys = []
driver_tsv = Path(evidence_dir) / "driver" / "driver-evidence.tsv"
if driver_tsv.exists():
    for line in driver_tsv.read_text(encoding="utf-8").splitlines():
        label = line.split("\t", 1)[0]
        driver_keys.append(label)
passed = [row["label"] for row in rows if row["status"] == "passed"]
blocked = [row["label"] for row in rows if row["status"] == "blocked"]
failed = [row["label"] for row in rows if row["status"] == "failed"]
if failed:
    java_status = "failed"
elif blocked:
    java_status = "blocked-pending-plan194-stop"
elif passed:
    java_status = "passed-via-java-2.13.0"
else:
    java_status = "failed"
evidence = {
    "schema": "i2pr-m6-java-v1",
    "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    "i2pr_commit": commit,
    "os_image": platform.platform(),
    "rust_toolchain": rustc,
    "execution_lane": "m6-java-external",
    "ssu2_bind_policy": "127.0.0.1 loopback only, advertise=false, no introducer",
    "java_i2p": {
        "repository": "https://github.com/i2p/i2p.i2p.git",
        "revision": java_pin,
        "version": java_version,
        "role": "mandatory second-family mixed-router reference, unmodified",
        "transit": "loopback-only, no public reseed, SAM loopback (Plan 194 only)",
        "datadir": "fresh per-run scratch dir under i2p.dir.config",
    },
    "driver_evidence_keys": driver_keys,
    "results": rows,
    "m6_java": java_status,
    "passed_labels": passed,
    "blocked_labels": blocked,
    "failed_labels": failed,
    "known_limitations": [
        "second-family Java qualification: i2pd first-family passed via Plan 193",
        "loopback-only Java reference; no public I2P participation",
        "no Java second-family Streaming claim until Plan 194 §5.5 rows flip passed",
    ],
}
out = Path(evidence_dir)
out.mkdir(parents=True, exist_ok=True)
(out / "evidence.json").write_text(json.dumps(evidence, indent=2, sort_keys=True) + "\n")
with (out / "evidence.md").open("w", encoding="utf-8") as stream:
    stream.write("# Plan 194 M6 Java I2P second-family qualification evidence\n\n")
    stream.write(f"- i2pr commit: `{commit}`\n")
    stream.write(f"- Java I2P: `{java_version}` @ `{java_pin}` (unmodified)\n")
    stream.write(f"- OS/image: `{platform.platform()}`\n")
    stream.write(f"- Rust: `{rustc}`\n")
    stream.write("- Bind policy: `127.0.0.1` only, `advertise=false`, no introducer\n")
    stream.write("- Java profile: `i2p.dir.config=scratch`, `reseed.enable=false`, SAM loopback\n\n")
    stream.write("| Result | Status | Detail |\n| --- | --- | --- |\n")
    for row in rows:
        stream.write(f"| {row['label']} | {row['status']} | {row['detail']} |\n")
PY

if [[ "${REQUIRED_FAILED}" -ne 0 ]]; then
  echo "Plan 194 M6 Java I2P second-family lane failed; sanitized evidence: ${EVIDENCE_DIR}" >&2
  exit 1
fi
echo "Plan 194 M6 Java I2P second-family lane passed; sanitized evidence: ${EVIDENCE_DIR}"
