//! Plan 177 SOCKS5 client profile configuration and central hard
//! ceilings used across the SOCKS5 module.
//!
//! Plan 173 §6/§3.1 require every length, count, deadline, and
//! generated byte region to have a hard typed ceiling. This module
//! exposes those constants together with the per-service
//! [`Socks5ClientOptions`] surface the daemon parses from TOML and
//! passes to the runtime-neutral SOCKS5 module.

#![forbid(unsafe_code)]

use std::collections::BTreeSet;

use crate::destination::validate_static_alias;
use crate::errors::ServiceTunnelError;

/// Maximum number of methods offered by a client in the greeting.
pub const SOCKS5_METHOD_COUNT_MAX: usize = 16;
/// Maximum bytes for the greeting section
/// (`VER + NMETHODS + METHODS`).
pub const SOCKS5_GREETING_MAX_BYTES: usize = 32;
/// Maximum bytes for the request header section
/// (`VER + CMD + RSV + ATYP`).
pub const SOCKS5_REQUEST_HEADER_MAX_BYTES: usize = 32;
/// Maximum length of the DOMAINNAME address field (RFC field is
/// u8; Plan 177 hard caps at 255 bytes).
pub const SOCKS5_DOMAIN_MAX_BYTES: usize = 255;
/// Maximum retained bytes before a complete greeting+request.
pub const SOCKS5_RETAINED_BUFFER_MAX_BYTES: usize = 320;
/// Maximum bytes for one generated SOCKS5 reply.
pub const SOCKS5_REPLY_MAX_BYTES: usize = 64;
/// Maximum SOCKS5-specific options-set entries (e.g. CONNECT ports,
/// allowed destinations list).
pub const SOCKS5_OPTIONS_MAX_PORTS: usize = 16;

/// SOCKS5 no-authentication reply (VER + selected method).
pub const SOCKS5_NO_AUTH_REPLY: [u8; 2] = [0x05, 0x00];
/// SOCKS5 no-acceptable-method reply (VER + 0xff).
pub const SOCKS5_NO_ACCEPTABLE_METHOD_REPLY: [u8; 2] = [0x05, 0xff];

/// SOCKS version byte (VER) for both greeting and request.
pub const SOCKS_VERSION: u8 = 0x05;
/// SOCKS5 no-authentication method byte.
pub const SOCKS5_METHOD_NO_AUTH: u8 = 0x00;
/// SOCKS5 username/password method byte (rejected).
pub const SOCKS5_METHOD_USER_PASS: u8 = 0x02;
/// SOCKS5 CONNECT command byte.
pub const SOCKS5_CMD_CONNECT: u8 = 0x01;
/// SOCKS5 BIND command byte (rejected).
pub const SOCKS5_CMD_BIND: u8 = 0x02;
/// SOCKS5 UDP ASSOCIATE command byte (rejected).
pub const SOCKS5_CMD_UDP_ASSOCIATE: u8 = 0x03;
/// SOCKS5 reserved byte in request header (must be 0x00).
pub const SOCKS5_RESERVED: u8 = 0x00;
/// SOCKS5 IPv4 address-type byte (rejected).
pub const SOCKS5_ATYP_IPV4: u8 = 0x01;
/// SOCKS5 DOMAINNAME address-type byte (the only M10 form).
pub const SOCKS5_ATYP_DOMAIN: u8 = 0x03;
/// SOCKS5 IPv6 address-type byte (rejected).
pub const SOCKS5_ATYP_IPV6: u8 = 0x04;

/// Default CONNECT target port (HTTPS port 443, identical to the
/// M10 HTTP CONNECT default policy).
pub const DEFAULT_CONNECT_PORT: u16 = 443;

/// CONNECT allowed-port policy used by the SOCKS5 client profile.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConnectPortPolicy {
    /// Allowed CONNECT target ports (canonical HTTPS plus any
    /// additional explicit I2P destination ports configured for the
    /// tunnel). Empty set is rejected at validation; port 443 is
    /// always implied as the default CONNECT port policy unless
    /// the operator explicitly overrides it.
    pub connect_allowed_ports: BTreeSet<u16>,
}

impl Default for ConnectPortPolicy {
    fn default() -> Self {
        let mut ports = BTreeSet::new();
        ports.insert(DEFAULT_CONNECT_PORT);
        Self {
            connect_allowed_ports: ports,
        }
    }
}

impl ConnectPortPolicy {
    /// Returns the Plan 177 default policy.
    pub fn defaults() -> Self {
        Self::default()
    }

    /// Validates the policy. The CONNECT allowed port set must be
    /// non-empty and may not exceed the ceiling. Port 443 is
    /// permitted but not required.
    pub fn validate(&self) -> Result<(), ServiceTunnelError> {
        if self.connect_allowed_ports.is_empty() {
            return Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "CONNECT allowed ports must contain at least one port",
            });
        }
        if self.connect_allowed_ports.len() > SOCKS5_OPTIONS_MAX_PORTS {
            return Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "CONNECT allowed ports exceed the per-tunnel ceiling",
            });
        }
        Ok(())
    }

    /// Returns `true` when the supplied port is allowed by the
    /// CONNECT port policy.
    pub fn allows_connect_port(&self, port: u16) -> bool {
        self.connect_allowed_ports.contains(&port)
    }
}

/// SOCKS5 client profile options attached to a `ServiceTunnelSpec`
/// whose `kind` is `Socks5Client`.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Socks5ClientOptions {
    /// CONNECT allowed-port policy.
    pub port_policy: ConnectPortPolicy,
    /// Maximum I2P destination ports to advertise via the
    /// destination reference; used by the daemon to validate that
    /// the configured remote destination accepts the requested
    /// port. Empty means "any port allowed by the remote
    /// destination; proxy does not enforce a port choice here".
    pub destination_ports: BTreeSet<u16>,
    /// Explicit list of `.i2p` host suffixes or full `.i2p`
    /// destinations the proxy will accept. When empty, any valid
    /// `.i2p` host is accepted (subject to Base32/alias resolution).
    pub allowed_hosts: Vec<String>,
}

impl Socks5ClientOptions {
    /// Returns the Plan 177 default policy.
    pub fn defaults() -> Self {
        Self::default()
    }

    /// Validates the SOCKS5 profile options structurally.
    pub fn validate(&self) -> Result<(), ServiceTunnelError> {
        self.port_policy.validate()?;
        if self.destination_ports.len() > SOCKS5_OPTIONS_MAX_PORTS {
            return Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "destination ports exceed the per-tunnel ceiling",
            });
        }
        for host in &self.allowed_hosts {
            validate_static_alias(host)?;
        }
        if self.allowed_hosts.len() > SOCKS5_OPTIONS_MAX_PORTS {
            return Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "allowed hosts exceed the per-tunnel ceiling",
            });
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn port_policy_defaults_to_https_only() {
        let policy = ConnectPortPolicy::default();
        assert!(policy.allows_connect_port(443));
        assert!(!policy.allows_connect_port(80));
        assert!(policy.validate().is_ok());
    }

    #[test]
    fn port_policy_rejects_empty_ports() {
        let policy = ConnectPortPolicy {
            connect_allowed_ports: BTreeSet::new(),
        };
        assert!(policy.validate().is_err());
    }

    #[test]
    fn socks5_options_default_validate() {
        let options = Socks5ClientOptions::defaults();
        options.validate().expect("defaults validate");
    }

    #[test]
    fn allowed_hosts_reject_malformed_alias() {
        let mut options = Socks5ClientOptions::defaults();
        options.allowed_hosts.push("BAD_UPPER.i2p".to_owned());
        assert!(options.validate().is_err());
    }
}
