[package]
name = "i2pr-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Local I2P destination lifecycle, destination tunnel pools, and LeaseSet2 generation"
publish = false

[dependencies]
i2pr-core = { path = "../i2pr-core" }
i2pr-crypto = { path = "../i2pr-crypto" }
i2pr-netdb = { path = "../i2pr-netdb" }
i2pr-proto = { path = "../i2pr-proto" }
i2pr-tunnel = { path = "../i2pr-tunnel" }
rand_chacha.workspace = true
rand_core = { workspace = true }
thiserror.workspace = true
x25519-dalek = { workspace = true, features = ["static_secrets"] }
zeroize.workspace = true

[dev-dependencies]
rand_core = { workspace = true, features = ["std", "os_rng"] }

[lints]
workspace = true
