//! Plan 176 HTTP client profile configuration and central hard
//! ceilings used across the HTTP module.
//!
//! Plan 173 §6/§3.1 require every length, count, deadline, and
//! generated byte region to have a hard typed ceiling. This module
//! exposes those constants together with the per-service
//! [`HttpClientOptions`] surface the daemon parses from TOML and
//! passes to the runtime-neutral HTTP module.

#![forbid(unsafe_code)]

use std::collections::BTreeSet;

use crate::destination::validate_static_alias;
use crate::errors::ServiceTunnelError;

/// Maximum request line bytes (including CRLF).
pub const HTTP_REQUEST_LINE_MAX_BYTES: usize = 8192;
/// Maximum total header bytes (header lines + final CRLF).
pub const HTTP_TOTAL_HEADER_MAX_BYTES: usize = 65_536;
/// Maximum header count.
pub const HTTP_HEADER_COUNT_MAX: usize = 100;
/// Maximum field name bytes.
pub const HTTP_FIELD_NAME_MAX_BYTES: usize = 256;
/// Maximum field value bytes.
pub const HTTP_FIELD_VALUE_MAX_BYTES: usize = 8192;
/// Maximum CONNECT authority bytes.
pub const HTTP_CONNECT_AUTHORITY_MAX_BYTES: usize = 512;
/// Maximum retained buffered bytes before a complete header section.
pub const HTTP_RETAINED_BUFFER_MAX_BYTES: usize = 65_536;
/// Maximum bytes for one generated error response.
pub const HTTP_ERROR_RESPONSE_MAX_BYTES: usize = 1024;
/// Maximum HTTP-specific options-set entries (e.g. CONNECT ports,
/// allowed destinations list).
pub const HTTP_OPTIONS_MAX_PORTS: usize = 16;

/// Default User-Agent substitution value used by the conservative
/// privacy profile.
pub const DEFAULT_USER_AGENT_VALUE: &str = "i2pr/0.1";

/// User-Agent header policy applied by the rewrite pass.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, Hash)]
pub enum UserAgentPolicy {
    /// Forward the original User-Agent unchanged.
    Keep,
    /// Remove the User-Agent header entirely.
    Strip,
    /// Replace the User-Agent with the stable Plan 176 value.
    #[default]
    ReplaceStable,
}

impl UserAgentPolicy {
    /// Parses one kebab-case policy spelling.
    pub fn parse(value: &str) -> Result<Self, ServiceTunnelError> {
        match value {
            "keep" => Ok(Self::Keep),
            "strip" => Ok(Self::Strip),
            "replace-stable" | "replace_stable" => Ok(Self::ReplaceStable),
            _ => Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "user-agent policy must be keep, strip, or replace-stable",
            }),
        }
    }
}

/// Privacy/hop-by-hop policy used by the rewrite pass.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PrivacyPolicy {
    /// User-Agent handling.
    pub user_agent: UserAgentPolicy,
    /// Strip `Referer` before forwarding.
    pub strip_referer: bool,
    /// Strip `From` before forwarding.
    pub strip_from: bool,
    /// Allowed CONNECT target ports (canonical HTTPS plus any
    /// additional explicit I2P destination ports configured for the
    /// tunnel). Empty set is rejected at validation; port 443 is
    /// always implied as the default CONNECT port policy unless
    /// the operator explicitly overrides it.
    pub connect_allowed_ports: BTreeSet<u16>,
}

impl Default for PrivacyPolicy {
    fn default() -> Self {
        let mut ports = BTreeSet::new();
        ports.insert(443);
        Self {
            user_agent: UserAgentPolicy::ReplaceStable,
            strip_referer: true,
            strip_from: true,
            connect_allowed_ports: ports,
        }
    }
}

impl PrivacyPolicy {
    /// Validates the policy. The CONNECT allowed port set must be
    /// non-empty and may not exceed the ceiling. Port 443 is
    /// permitted but not required.
    pub fn validate(&self) -> Result<(), ServiceTunnelError> {
        if self.connect_allowed_ports.is_empty() {
            return Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "CONNECT allowed ports must contain at least one port",
            });
        }
        if self.connect_allowed_ports.len() > HTTP_OPTIONS_MAX_PORTS {
            return Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "CONNECT allowed ports exceed the per-tunnel ceiling",
            });
        }
        Ok(())
    }

    /// Returns `true` when the supplied port is allowed by the
    /// CONNECT port policy.
    pub fn allows_connect_port(&self, port: u16) -> bool {
        self.connect_allowed_ports.contains(&port)
    }
}

/// HTTP client profile options attached to a `ServiceTunnelSpec`
/// whose `kind` is `HttpClient`.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct HttpClientOptions {
    /// Privacy/hop-by-hop rewrite policy.
    pub privacy: PrivacyPolicy,
    /// Maximum I2P destination ports to advertise via the
    /// destination reference; used by the daemon to validate that
    /// the configured remote destination accepts the requested
    /// port. Empty means "any port allowed by the remote
    /// destination; proxy does not enforce a port choice here".
    pub destination_ports: BTreeSet<u16>,
    /// Explicit list of `.i2p` host suffixes or full `.i2p`
    /// destinations the proxy will accept. When empty, any valid
    /// `.i2p` host is accepted (subject to Base32/alias resolution).
    pub allowed_hosts: Vec<String>,
}

impl HttpClientOptions {
    /// Returns the Plan 176 default policy.
    pub fn defaults() -> Self {
        Self::default()
    }

    /// Validates the HTTP profile options structurally.
    pub fn validate(&self) -> Result<(), ServiceTunnelError> {
        self.privacy.validate()?;
        if self.destination_ports.len() > HTTP_OPTIONS_MAX_PORTS {
            return Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "destination ports exceed the per-tunnel ceiling",
            });
        }
        for host in &self.allowed_hosts {
            validate_static_alias(host)?;
        }
        if self.allowed_hosts.len() > HTTP_OPTIONS_MAX_PORTS {
            return Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "allowed hosts exceed the per-tunnel ceiling",
            });
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_agent_policy_parses() {
        assert_eq!(
            UserAgentPolicy::parse("keep").expect("keep"),
            UserAgentPolicy::Keep
        );
        assert_eq!(
            UserAgentPolicy::parse("strip").expect("strip"),
            UserAgentPolicy::Strip
        );
        assert_eq!(
            UserAgentPolicy::parse("replace-stable").expect("replace"),
            UserAgentPolicy::ReplaceStable
        );
        assert!(UserAgentPolicy::parse("rewrite").is_err());
        assert!(UserAgentPolicy::parse("").is_err());
    }

    #[test]
    fn privacy_policy_defaults_to_https_only() {
        let policy = PrivacyPolicy::default();
        assert!(policy.allows_connect_port(443));
        assert!(!policy.allows_connect_port(80));
        assert!(policy.validate().is_ok());
    }

    #[test]
    fn privacy_policy_rejects_empty_ports() {
        let policy = PrivacyPolicy {
            connect_allowed_ports: BTreeSet::new(),
            ..PrivacyPolicy::default()
        };
        assert!(policy.validate().is_err());
    }

    #[test]
    fn allowed_hosts_reject_malformed_alias() {
        let mut options = HttpClientOptions::default();
        options.allowed_hosts.push("BAD_UPPER.i2p".to_owned());
        assert!(options.validate().is_err());
    }
}
