//! Plan 111 frozen independent conformance vectors.
//!
//! This module owns the fixed cryptographic vectors the Plan 111
//! conformance suite asserts against. The expected values are
//! produced by an **independent reference computation** that uses
//! only the low-level crypto primitives (`x25519-dalek`,
//! `sha2`, `chacha20poly1305`, `hkdf`) — never the production
//! [`crate::build_crypto::BuildCryptography`] trait — and the
//! resulting bytes are frozen as Rust constants. Every conformance
//! test then asserts that the production primitive reaches the
//! same bytes for the same inputs.
//!
//! Provenance: the values were generated by
//! `tests/integration/tunnel/conformance_vectors.rs::print_plan111_fixed_vectors`
//! once during the Plan 111 implementation pass; the script uses
//! the same primitives without ever calling into `i2pr-tunnel`.
//! The frozen constants are committed verbatim below.
//!
//! A defect in either the production code or the independent
//! reference code will now cause the conformance tests to fail
//! closed; the production primitive can no longer silently mask a
//! regression in its own transcript state.
#![forbid(unsafe_code)]

/// Length of the canonical X25519 ephemeral key in bytes.
pub const EPHEMERAL_KEY_LEN: usize = 32;
/// Length of the truncated hop identity-hash prefix.
pub const HASH_PREFIX_LEN: usize = 16;
/// Length of a ChaCha20-Poly1305 AEAD key.
pub const AEAD_KEY_LEN: usize = 32;
/// Length of a ChaCha20-Poly1305 authentication tag.
pub const TAG_LEN: usize = 16;
/// Length of a ChaCha20-Poly1305 nonce.
pub const AEAD_NONCE_LEN: usize = 12;
/// Length of a 154-byte request plaintext.
pub const SHORT_REQUEST_PLAINTEXT_SIZE: usize = 154;
/// Length of the sealed record envelope.
pub const SHORT_BUILD_RECORD_SIZE: usize = 218;

/// Canonical Noise-N protocol name used for the short tunnel-build
/// transcript. The exact 31-byte ASCII literal
/// `Noise_N_25519_ChaChaPoly_SHA256`.
pub const NOISE_PROTOCOL_NAME: &[u8] = b"Noise_N_25519_ChaChaPoly_SHA256";

/// Canonical null-prologue transcript hash (post `MixHash(empty)`)
/// for the short tunnel-build Noise-N transcript. Computed as
/// `SHA256(protocol_name || 0..=31)` per the canonical Noise spec.
pub const NULL_PROLOGUE_HASH: [u8; 32] = [
    105, 77, 82, 68, 90, 39, 217, 173, 250, 210, 156, 118, 50, 57, 93, 193, 228, 53, 76, 105, 180,
    249, 46, 172, 138, 30, 228, 106, 158, 210, 21, 84,
];

/// Hop static X25519 private key used by the frozen vectors.
pub const FIXED_HOP_PRIVATE: [u8; 32] = [
    0x55, 0x66, 0x77, 0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x00, 0x11, 0x22, 0x33, 0x44,
    0x55, 0x66, 0x77, 0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x00, 0x11, 0x22, 0x33, 0x44,
];

/// Hop static X25519 public key (computed by `x25519-dalek` against
/// `FIXED_HOP_PRIVATE`).
pub const FIXED_HOP_PUBLIC: [u8; 32] = [
    186, 210, 251, 152, 247, 32, 243, 217, 123, 161, 204, 237, 214, 124, 241, 148, 63, 200, 229,
    41, 158, 226, 65, 9, 221, 45, 80, 144, 175, 46, 135, 79,
];

/// Sender ephemeral X25519 private key used by the frozen vectors.
pub const FIXED_EPHEMERAL_PRIVATE: [u8; 32] = [
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10,
    0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, 0x20,
];

/// Sender ephemeral X25519 public key (computed by `x25519-dalek`
/// against `FIXED_EPHEMERAL_PRIVATE`).
pub const FIXED_EPHEMERAL_PUBLIC: [u8; 32] = [
    7, 163, 124, 188, 20, 32, 147, 200, 183, 85, 220, 27, 16, 232, 108, 180, 38, 55, 74, 209, 106,
    168, 83, 237, 11, 223, 192, 178, 184, 109, 28, 124,
];

/// Truncated 16-byte hop identity hash used by the frozen vectors.
pub const FIXED_HOP_IDENTITY: [u8; 32] = [0x99; 32];

/// 154-byte request plaintext used by the frozen vectors. The
/// plaintext content does not affect the transcript; the same
/// expected bytes apply for any 154-byte input.
pub const FIXED_REQUEST_PLAINTEXT: [u8; SHORT_REQUEST_PLAINTEXT_SIZE] = {
    let mut bytes = [0u8; SHORT_REQUEST_PLAINTEXT_SIZE];
    let mut value: u8 = 0;
    let mut i = 0;
    while i < SHORT_REQUEST_PLAINTEXT_SIZE {
        bytes[i] = value;
        value = value.wrapping_add(7);
        i += 1;
    }
    bytes
};

/// Frozen expected transcript hash after the static-key `MixHash`,
/// the ephemeral-key `MixHash`, and the post-AEAD
/// `MixHash(ciphertext || tag)`. This is the value the production
/// `NoiseRequestState::transcript_hash()` returns after sealing the
/// canonical request, and it is the AEAD associated data the
/// hop-own reply AEAD uses.
pub const POST_REQUEST_H: [u8; 32] = [
    220, 83, 39, 41, 251, 245, 234, 181, 30, 48, 12, 124, 55, 217, 173, 152, 53, 246, 244, 208,
    222, 73, 243, 143, 229, 1, 101, 117, 25, 89, 94, 57,
];

/// Frozen expected X25519 shared secret
/// `X25519(FIXED_EPHEMERAL_PRIVATE, FIXED_HOP_PUBLIC)`.
pub const FIXED_SHARED_SECRET: [u8; 32] = [
    197, 132, 162, 91, 151, 126, 34, 18, 199, 170, 6, 80, 189, 137, 151, 119, 42, 200, 8, 69, 194,
    11, 218, 248, 188, 66, 123, 242, 84, 206, 76, 77,
];

/// Frozen 64-byte HKDF output for the request `es` derivation
/// (`HKDF(ck, sharedSecret, "", 64)` after the ephemeral mix).
pub const FIXED_REQUEST_KEYDATA: [u8; 64] = [
    210, 235, 145, 225, 195, 156, 188, 119, 107, 254, 171, 249, 230, 174, 44, 80, 108, 181, 26, 92,
    120, 51, 160, 2, 231, 180, 149, 106, 169, 243, 224, 140, 2, 78, 33, 13, 196, 143, 41, 225, 233,
    110, 247, 59, 41, 53, 246, 35, 138, 107, 28, 220, 243, 237, 200, 248, 137, 134, 228, 138, 91,
    105, 239, 171,
];

/// Frozen post-request chaining key (`FIXED_REQUEST_KEYDATA[0..32]`).
pub const FIXED_POST_REQUEST_CK: [u8; 32] = [
    210, 235, 145, 225, 195, 156, 188, 119, 107, 254, 171, 249, 230, 174, 44, 80, 108, 181, 26, 92,
    120, 51, 160, 2, 231, 180, 149, 106, 169, 243, 224, 140,
];

/// Frozen request AEAD key (`FIXED_REQUEST_KEYDATA[32..64]`).
pub const FIXED_REQUEST_AEAD_KEY: [u8; 32] = [
    2, 78, 33, 13, 196, 143, 41, 225, 233, 110, 247, 59, 41, 53, 246, 35, 138, 107, 28, 220, 243,
    237, 200, 248, 137, 134, 228, 138, 91, 105, 239, 171,
];

/// Frozen 218-byte sealed envelope produced by the canonical
/// `EciesX25519BuildCryptography::seal_short_request_with_ephemeral`
/// over the canonical fixed inputs above. Layout:
/// `truncated_hop_hash (16) || ephemeral_pub (32) || ciphertext (154)
/// || tag (16)`.
pub const FIXED_SEALED_REQUEST: [u8; SHORT_BUILD_RECORD_SIZE] = [
    153, 153, 153, 153, 153, 153, 153, 153, 153, 153, 153, 153, 153, 153, 153, 153, 7, 163, 124,
    188, 20, 32, 147, 200, 183, 85, 220, 27, 16, 232, 108, 180, 38, 55, 74, 209, 106, 168, 83, 237,
    11, 223, 192, 178, 184, 109, 28, 124, 84, 114, 187, 93, 11, 221, 137, 31, 40, 72, 39, 48, 140,
    7, 144, 252, 87, 34, 35, 35, 194, 112, 146, 13, 70, 95, 176, 220, 100, 190, 218, 222, 28, 199,
    253, 148, 33, 0, 158, 140, 180, 3, 103, 90, 105, 187, 181, 160, 168, 109, 33, 115, 227, 190,
    66, 82, 54, 146, 166, 150, 205, 46, 157, 26, 122, 14, 44, 167, 67, 35, 181, 59, 24, 74, 6, 67,
    235, 179, 115, 59, 31, 117, 227, 6, 115, 210, 1, 173, 89, 106, 167, 133, 0, 209, 28, 72, 108,
    179, 244, 57, 25, 54, 208, 111, 199, 127, 241, 138, 35, 91, 67, 130, 141, 39, 43, 60, 14, 60,
    42, 19, 172, 170, 6, 39, 15, 194, 19, 147, 180, 58, 191, 174, 97, 224, 120, 37, 192, 190, 129,
    173, 9, 54, 237, 214, 159, 15, 201, 220, 183, 164, 27, 139, 17, 214, 27, 168, 180, 46, 125, 10,
    146, 213, 87, 133, 177, 50, 17, 207, 178, 242,
];

/// Frozen 12-byte ChaChaPoly nonce for record slot 5. The slot byte
/// lives at offset 4; bytes 0..3 and 5..11 are zero.
pub const FIXED_SLOT_FIVE_NONCE: [u8; AEAD_NONCE_LEN] = [
    0x00, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

/// Frozen 12-byte ChaCha20 IV for record slot 3. The slot byte lives
/// at offset 4; bytes 0..3 and 5..11 are zero.
pub const FIXED_SLOT_THREE_CHACHA20_IV: [u8; AEAD_NONCE_LEN] = [
    0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

/// Frozen `replyKey` derived from `SMTunnelReplyKey` over the
/// canonical post-request chaining key.
pub const FIXED_REPLY_KEY: [u8; 32] = [
    195, 34, 12, 152, 188, 160, 153, 67, 6, 54, 79, 51, 255, 121, 117, 47, 48, 12, 244, 205, 148,
    52, 52, 180, 158, 26, 201, 41, 114, 85, 142, 132,
];

/// Frozen `layerKey` derived from `SMTunnelLayerKey` over the
/// canonical post-request chaining key.
pub const FIXED_LAYER_KEY: [u8; 32] = [
    90, 219, 250, 164, 55, 138, 208, 158, 62, 163, 124, 72, 122, 183, 78, 158, 67, 128, 251, 216,
    132, 244, 11, 217, 45, 116, 81, 213, 25, 38, 0, 43,
];

/// Frozen `ivKey` derived from the post-`SMTunnelLayerKey`
/// continuation for the non-OBEP path.
pub const FIXED_IV_KEY: [u8; 32] = [
    2, 178, 139, 77, 112, 99, 255, 84, 101, 191, 59, 30, 89, 193, 106, 73, 200, 28, 231, 221, 99,
    56, 74, 151, 123, 187, 131, 62, 152, 52, 228, 155,
];

/// Frozen 8-byte OBEP garlic reply tag.
pub const FIXED_OBEP_GARLIC_TAG: [u8; 8] = [153, 171, 210, 118, 190, 253, 10, 89];

/// Frozen 32-byte OBEP garlic reply key.
pub const FIXED_OBEP_GARLIC_KEY: [u8; 32] = [
    127, 22, 246, 118, 238, 42, 83, 29, 170, 217, 13, 178, 126, 21, 4, 81, 249, 185, 184, 235, 68,
    61, 213, 157, 122, 245, 58, 139, 23, 45, 224, 237,
];

#[cfg(test)]
mod tests {
    use super::*;

    /// Sanity check: the frozen constants are exactly the lengths
    /// the protocol mandates. A regression that changes the
    /// canonical sizes fails this test before any cryptographic
    /// comparison runs.
    #[test]
    fn frozen_constants_have_canonical_lengths() {
        assert_eq!(FIXED_HOP_PRIVATE.len(), EPHEMERAL_KEY_LEN);
        assert_eq!(FIXED_HOP_PUBLIC.len(), EPHEMERAL_KEY_LEN);
        assert_eq!(FIXED_EPHEMERAL_PRIVATE.len(), EPHEMERAL_KEY_LEN);
        assert_eq!(FIXED_EPHEMERAL_PUBLIC.len(), EPHEMERAL_KEY_LEN);
        assert_eq!(FIXED_REQUEST_PLAINTEXT.len(), SHORT_REQUEST_PLAINTEXT_SIZE);
        assert_eq!(FIXED_SEALED_REQUEST.len(), SHORT_BUILD_RECORD_SIZE);
        assert_eq!(FIXED_SLOT_FIVE_NONCE.len(), AEAD_NONCE_LEN);
        assert_eq!(FIXED_SLOT_THREE_CHACHA20_IV.len(), AEAD_NONCE_LEN);
        assert_eq!(FIXED_REPLY_KEY.len(), AEAD_KEY_LEN);
        assert_eq!(FIXED_LAYER_KEY.len(), AEAD_KEY_LEN);
        assert_eq!(FIXED_IV_KEY.len(), AEAD_KEY_LEN);
        assert_eq!(FIXED_OBEP_GARLIC_TAG.len(), 8);
        assert_eq!(FIXED_OBEP_GARLIC_KEY.len(), 32);
    }

    /// The frozen null-prologue hash must match `SHA256` of the
    /// padded protocol name.
    #[test]
    fn null_prologue_hash_matches_sha256_of_padded_protocol_name() {
        use sha2::{Digest, Sha256};
        let mut padded = [0_u8; 32];
        padded[..NOISE_PROTOCOL_NAME.len()].copy_from_slice(NOISE_PROTOCOL_NAME);
        let mut hasher = Sha256::new();
        hasher.update(padded);
        let output = hasher.finalize();
        let mut expected = [0_u8; 32];
        expected.copy_from_slice(&output);
        assert_eq!(NULL_PROLOGUE_HASH, expected);
    }

    /// Slot nonce for slot `n` must place the slot byte at offset 4.
    #[test]
    fn slot_nonce_placement_matches_constant() {
        assert_eq!(FIXED_SLOT_FIVE_NONCE[4], 5);
        for i in [0usize, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11] {
            assert_eq!(FIXED_SLOT_FIVE_NONCE[i], 0);
        }
    }

    /// ChaCha20 IV for slot `n` must place the slot byte at offset 4.
    #[test]
    fn chacha20_iv_placement_matches_constant() {
        assert_eq!(FIXED_SLOT_THREE_CHACHA20_IV[4], 3);
        for i in [0usize, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11] {
            assert_eq!(FIXED_SLOT_THREE_CHACHA20_IV[i], 0);
        }
    }

    /// Independent reference computation uses only low-level
    /// primitives. The frozen constants must agree with this
    /// oracle; otherwise a defect in either side will fail the
    /// test.
    #[test]
    fn independent_oracle_agrees_with_frozen_constants() {
        use sha2::{Digest, Sha256};

        // Null-prologue `h = SHA256(padded_protocol_name)`.
        let mut padded = [0_u8; 32];
        padded[..NOISE_PROTOCOL_NAME.len()].copy_from_slice(NOISE_PROTOCOL_NAME);
        let mut hasher = Sha256::new();
        hasher.update(padded);
        let output = hasher.finalize();
        let mut computed = [0_u8; 32];
        computed.copy_from_slice(&output);
        assert_eq!(computed, NULL_PROLOGUE_HASH);

        // X25519 hop public key.
        let secret = x25519_dalek::StaticSecret::from(FIXED_HOP_PRIVATE);
        let public = x25519_dalek::PublicKey::from(&secret);
        assert_eq!(public.to_bytes(), FIXED_HOP_PUBLIC);

        // X25519 ephemeral public key.
        let eph_secret = x25519_dalek::StaticSecret::from(FIXED_EPHEMERAL_PRIVATE);
        let eph_public = x25519_dalek::PublicKey::from(&eph_secret);
        assert_eq!(eph_public.to_bytes(), FIXED_EPHEMERAL_PUBLIC);

        // X25519 shared secret (sender ephemeral private, hop
        // public).
        let shared = eph_secret.diffie_hellman(&public);
        assert_eq!(shared.as_bytes(), &FIXED_SHARED_SECRET[..]);

        // Transcript hash chain. Steps 1-3 produce the
        // post-ephemeral-h; the production then performs the
        // post-AEAD MixHash that yields POST_REQUEST_H.
        let mut h = NULL_PROLOGUE_HASH;
        let mut hasher = Sha256::new();
        hasher.update(h);
        hasher.update(FIXED_HOP_PUBLIC);
        let output = hasher.finalize();
        h.copy_from_slice(&output);
        let mut hasher = Sha256::new();
        hasher.update(h);
        hasher.update(FIXED_EPHEMERAL_PUBLIC);
        let output = hasher.finalize();
        h.copy_from_slice(&output);
        // POST_REQUEST_H == MixHash(h || ciphertext || tag). The
        // ciphertext bytes for the canonical request are the
        // ciphertext portion of FIXED_SEALED_REQUEST.
        let ciphertext_with_tag = &FIXED_SEALED_REQUEST[48..];
        let mut hasher = Sha256::new();
        hasher.update(h);
        hasher.update(ciphertext_with_tag);
        let output = hasher.finalize();
        h.copy_from_slice(&output);
        assert_eq!(h, POST_REQUEST_H);
    }

    /// Production `EciesX25519BuildCryptography::seal_short_request_with_ephemeral`
    /// must produce the canonical frozen envelope for the
    /// canonical fixed inputs. A defect in the production
    /// transcript state causes this test to fail closed.
    #[test]
    fn production_seal_short_request_matches_frozen_envelope() {
        use crate::build_crypto::BuildCryptography;
        let cryptography = crate::build_crypto::EciesX25519BuildCryptography::new();
        let sealed = cryptography
            .seal_short_request_with_ephemeral(
                &FIXED_REQUEST_PLAINTEXT,
                &FIXED_HOP_PUBLIC,
                &FIXED_HOP_IDENTITY,
                &FIXED_EPHEMERAL_PRIVATE,
            )
            .expect("seal");
        assert_eq!(
            sealed.record.as_ref(),
            &FIXED_SEALED_REQUEST[..],
            "production must match the frozen envelope layout"
        );
        assert_eq!(sealed.ephemeral_pub, FIXED_EPHEMERAL_PUBLIC);
        assert_eq!(
            sealed.state.transcript_hash(),
            POST_REQUEST_H,
            "production must match the frozen post-request transcript hash"
        );
        assert_eq!(
            sealed.state.chaining_key(),
            FIXED_POST_REQUEST_CK,
            "production must match the frozen post-request chaining key"
        );
    }

    /// Production `EciesX25519BuildCryptography::open_short_request`
    /// must reverse the canonical frozen envelope and reach the
    /// frozen post-request state.
    #[test]
    fn production_open_short_request_matches_frozen_state() {
        use crate::build_crypto::BuildCryptography;
        let cryptography = crate::build_crypto::EciesX25519BuildCryptography::new();
        let opened = cryptography
            .open_short_request(
                &FIXED_SEALED_REQUEST,
                &FIXED_HOP_PRIVATE,
                &FIXED_HOP_IDENTITY,
            )
            .expect("open");
        assert_eq!(opened.plaintext.as_ref(), &FIXED_REQUEST_PLAINTEXT[..]);
        assert_eq!(opened.state.transcript_hash(), POST_REQUEST_H);
        assert_eq!(opened.state.chaining_key(), FIXED_POST_REQUEST_CK);
    }

    /// Production `derive_layer_keys` must match the frozen
    /// `SMTunnel*` outputs for the canonical participant and OBEP
    /// continuations.
    #[test]
    fn production_derive_layer_keys_matches_frozen_outputs() {
        use crate::build_crypto::BuildCryptography;
        let cryptography = crate::build_crypto::EciesX25519BuildCryptography::new();
        let sealed = cryptography
            .seal_short_request_with_ephemeral(
                &FIXED_REQUEST_PLAINTEXT,
                &FIXED_HOP_PUBLIC,
                &FIXED_HOP_IDENTITY,
                &FIXED_EPHEMERAL_PRIVATE,
            )
            .expect("seal");
        let participant =
            crate::build_crypto::derive_layer_keys(&sealed.state, false).expect("participant");
        assert_eq!(participant.reply_key(), &FIXED_REPLY_KEY);
        assert_eq!(participant.layer_key(), &FIXED_LAYER_KEY);
        assert_eq!(participant.iv_key(), &FIXED_IV_KEY);
        let obep = crate::build_crypto::derive_layer_keys(&sealed.state, true).expect("obep");
        assert_eq!(
            obep.garlic_reply_key().expect("garlic key"),
            &FIXED_OBEP_GARLIC_KEY
        );
        assert_eq!(
            obep.garlic_reply_tag().expect("garlic tag"),
            &FIXED_OBEP_GARLIC_TAG
        );
    }

    /// Production `ValidatedRecordSlot::nonce()` must place the
    /// slot byte at offset 4 and produce the canonical
    /// 12-byte nonce.
    #[test]
    fn production_validated_record_slot_nonce_matches_constant() {
        let slot = crate::build_crypto::ValidatedRecordSlot::new(5).expect("slot");
        assert_eq!(slot.nonce(), FIXED_SLOT_FIVE_NONCE);
    }
}
