//! Plan 181 §6 remote independent-I2P qualification attempt.
//!
//! This test is `#[ignore]`d for ordinary libtest execution and runs
//! only through explicit selection by
//! `tests/integration/service-tunnels/run-independent.sh` (the same
//! fail-closed lane pattern as the SSU2 external driver). It must
//! never silently pass when its environment is absent.
//!
//! The test attempts one M10 generic-client Streaming connect to a
//! destination generated by the exact-pinned independent router
//! (i2pd 2.61.0 via SAM `DEST GENERATE`, public `PUB` material
//! passed through `I2PD_PEER_PUB_B64`). The current M10 product has
//! no tunnel/transport path to non-local destinations by design, so
//! the expected honest outcome is the §6.3 stop condition:
//! structurally valid peer, zero routes (`unknown_peer`), bounded
//! connect timeout. That failure is the counted evidence —
//! recorded as `blocked`, never as `passed` — and it must fail
//! closed (nonzero exit) if the independent peer material is
//! absent or structurally invalid.
//!
//! No private key material is read, logged, or asserted. The peer
//! `PUB` itself is never printed.

#![forbid(unsafe_code)]

use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use i2pr_runtime::{CancellationToken, ChildFailurePolicy, ChildScope};
use i2pr_service_tunnels::{
    DestinationPolicy, DestinationRef, LocalListenerSpec, ServerTarget, ServiceTimeouts,
    ServiceTunnelId, ServiceTunnelKind, ServiceTunnelSet, ServiceTunnelSpec, StaticAliasTable,
};
use tokio::io::AsyncWriteExt;
use tokio::net::TcpStream;

use i2pr_daemon::service_tunnels::{ServiceTunnelManager, ServiceTunnelManagerConfig};

fn temp_data_dir(name: &str) -> tempfile::TempDir {
    let directory = tempfile::Builder::new()
        .prefix(name)
        .tempdir()
        .expect("tempdir");
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(directory.path(), std::fs::Permissions::from_mode(0o700))
            .expect("set tempdir permissions");
    }
    directory
}

/// Attempts one client-tunnel connect to the independent peer and
/// returns the typed outcome. `established` is true only when the
/// Streaming handshake completes (the M6 debt says it cannot).
async fn attempt_remote_connect(peer_pub_b64: &str) -> (bool, usize, usize, u64) {
    let directory = temp_data_dir("m10-remote-qualify");
    let target_socket: SocketAddr = "127.0.0.1:9".parse().unwrap();
    let specs = vec![
        ServiceTunnelSpec {
            id: ServiceTunnelId::parse("alpha-remote-client").expect("id"),
            kind: ServiceTunnelKind::GenericClient,
            enabled: true,
            listener: Some(LocalListenerSpec::parse_socket("127.0.0.1:0").expect("listener")),
            target: None,
            targets: Vec::new(),
            destination: Some(DestinationRef::ConfiguredDestination(
                peer_pub_b64.to_owned(),
            )),
            policy: DestinationPolicy::Dedicated,
            max_connections: 2,
            max_buffered_bytes_per_direction: 65_536,
            timeouts: ServiceTimeouts::defaults(),
            http_options: None,
            socks5_options: None,
            irc_options: None,
        },
        ServiceTunnelSpec {
            id: ServiceTunnelId::parse("alpha-local-server").expect("id"),
            kind: ServiceTunnelKind::GenericServer,
            enabled: true,
            listener: None,
            target: Some(ServerTarget::LoopbackTcp(target_socket)),
            targets: Vec::new(),
            destination: None,
            policy: DestinationPolicy::Dedicated,
            max_connections: 2,
            max_buffered_bytes_per_direction: 65_536,
            timeouts: ServiceTimeouts::defaults(),
            http_options: None,
            socks5_options: None,
            irc_options: None,
        },
    ];
    let manager = Arc::new(
        ServiceTunnelManager::new(ServiceTunnelManagerConfig {
            data_dir: directory.path().to_path_buf(),
            aggregate_connection_ceiling: 8,
            per_service_connection_ceiling: 4,
            specs: Arc::new(ServiceTunnelSet { tunnels: specs }),
            aliases: Arc::new(StaticAliasTable::new()),
        })
        .expect("manager builds"),
    );
    // A structurally invalid peer PUB must fail here (proves the
    // material was actually parsed, so a later `unknown_peer` can
    // only mean "valid but unroutable").
    let runtimes = manager.prepare().await.expect("prepare");
    // Destination decode happens at resolve time (per connection),
    // so an invalid PUB surfaces as a failed connect, not a
    // prepare error. The caller distinguishes via counters.
    let cancel = CancellationToken::new();
    let scope = ChildScope::for_test(&cancel, ChildFailurePolicy::FailParent);
    manager
        .start_supervisors(runtimes, &scope, cancel.clone())
        .expect("supervisors started");
    let listener = manager
        .client_listener_address("alpha-remote-client")
        .expect("listener");
    let mut stream = TcpStream::connect(listener).await.expect("connect");
    stream
        .write_all(b"plan181-remote-qualification")
        .await
        .expect("write");
    // The connect deadline (10 s default) bounds this wait; the
    // pump exits when the Streaming handshake times out.
    let _ = tokio::time::sleep(Duration::from_secs(14)).await;
    let _ = stream.shutdown().await;
    let snapshot = manager.snapshot();
    let destination_id = manager
        .service_destination_id("alpha-remote-client")
        .expect("client destination id");
    let counters = manager.delivery_counters(destination_id);
    let established = snapshot.active_client_connections > 0;
    (
        established,
        counters.unknown_peer,
        counters.delivered,
        snapshot.failed_connects_total,
    )
    // `scope`/`cancel` drop here; the ChildScope owner ends the
    // supervised tasks. `directory` removal wipes key material.
}

#[tokio::test(flavor = "current_thread")]
#[ignore = "requires exact-pinned i2pd SAM peer (Plan 181 §6); run via tests/integration/service-tunnels/run-independent.sh"]
async fn m10_remote_independent_router_unreachable_blocker() {
    let peer_pub_b64 = std::env::var("I2PD_PEER_PUB_B64").unwrap_or_else(|_| {
        panic!(
            "I2PD_PEER_PUB_B64 is absent: provision exact-pinned i2pd and run \
             tests/integration/service-tunnels/run-independent.sh (never silently pass)"
        )
    });
    assert!(
        peer_pub_b64.len() >= 512,
        "peer PUB material is implausibly short; refusing to attempt"
    );
    let (established, unknown_peer, delivered, failed) =
        attempt_remote_connect(peer_pub_b64.trim()).await;
    // Sanitized facts only: counts and the blocker verdict. The
    // peer PUB is never printed.
    println!("REMOTE_QUALIFY_ESTABLISHED={}", u8::from(established));
    println!("REMOTE_QUALIFY_UNKNOWN_PEER={unknown_peer}");
    println!("REMOTE_QUALIFY_DELIVERED={delivered}");
    println!("REMOTE_QUALIFY_FAILED_CONNECTS={failed}");
    // Plan 181 §6.3 stop condition, asserted as specified: the
    // peer parses (unknown_peer, not a decode failure), nothing
    // routes (delivered == 0), nothing establishes, and the
    // attempt fails closed. If M6 mixed-router work ever lands,
    // this test flips red on purpose: the blocker is lifted and
    // the row must be re-counted as interop evidence.
    assert!(
        !established,
        "unexpected establishment: M6 blocker may be lifted; re-count this row as interop evidence"
    );
    assert!(
        unknown_peer > 0,
        "expected unknown_peer>0 (valid independent peer, no route); the attempt proved nothing"
    );
    assert_eq!(
        delivered, 0,
        "nothing may route to a non-local destination on the local product"
    );
    assert!(
        failed > 0,
        "the failed connect must be counted, never swallowed"
    );
}
