//! Typed I2CP session, message, nonce, and request identifiers.
//!
//! Widths follow the pinned I2CP specification: session IDs are two
//! bytes, message IDs and client nonces are four bytes, and
//! HostLookup request IDs are four bytes. Session ID `0xffff`
//! indicates "no session" (used by session-less HostLookup).

use std::fmt;

/// An I2CP session identifier (two bytes, big-endian on the wire).
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct SessionId(u16);

impl SessionId {
    /// The reserved "no session" identifier (`0xffff`).
    pub const NO_SESSION: Self = Self(0xffff);

    /// Wraps a raw session identifier.
    pub const fn new(raw: u16) -> Self {
        Self(raw)
    }

    /// Returns the raw identifier.
    pub const fn get(self) -> u16 {
        self.0
    }

    /// Reports whether this is the reserved "no session" value.
    pub const fn is_no_session(self) -> bool {
        self.0 == 0xffff
    }
}

impl fmt::Display for SessionId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}", self.0)
    }
}

/// An I2CP message identifier (four bytes, big-endian on the wire).
///
/// Message IDs are generated by the router and are unique within a
/// session only. They are not the same as the client nonce.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MessageId(u32);

impl MessageId {
    /// Wraps a raw message identifier.
    pub const fn new(raw: u32) -> Self {
        Self(raw)
    }

    /// Returns the raw identifier.
    pub const fn get(self) -> u32 {
        self.0
    }
}

impl fmt::Display for MessageId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}", self.0)
    }
}

/// A client-supplied I2CP nonce (four bytes, big-endian on the wire).
///
/// A zero nonce suppresses `MessageStatus` replies; a nonzero nonce
/// requests at least one status reply for the outbound message.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ClientNonce(u32);

impl ClientNonce {
    /// The nonce value that suppresses status replies.
    pub const NONE: Self = Self(0);

    /// Wraps a raw nonce.
    pub const fn new(raw: u32) -> Self {
        Self(raw)
    }

    /// Returns the raw nonce.
    pub const fn get(self) -> u32 {
        self.0
    }

    /// Reports whether status replies are requested.
    pub const fn wants_status(self) -> bool {
        self.0 != 0
    }
}

/// A HostLookup request identifier (four bytes, big-endian on the wire).
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct HostRequestId(u32);

impl HostRequestId {
    /// Wraps a raw request identifier.
    pub const fn new(raw: u32) -> Self {
        Self(raw)
    }

    /// Returns the raw identifier.
    pub const fn get(self) -> u32 {
        self.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_session_reserved_value() {
        assert_eq!(SessionId::NO_SESSION.get(), 0xffff);
        assert!(SessionId::NO_SESSION.is_no_session());
        assert!(!SessionId::new(0).is_no_session());
        assert!(!SessionId::new(0xfffe).is_no_session());
    }

    #[test]
    fn nonce_status_request_semantics() {
        assert!(!ClientNonce::NONE.wants_status());
        assert!(ClientNonce::new(1).wants_status());
    }
}
