[package]
name = "i2pr-netdb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Runtime-neutral RouterInfo validation, local NetDB foundation, SU3 reseed verification, and local signed RouterInfo construction for i2pr"
publish = false

[dependencies]
base64ct = { workspace = true }
i2pr-crypto = { path = "../i2pr-crypto" }
i2pr-proto = { path = "../i2pr-proto" }
rsa = { workspace = true }
sha2 = { workspace = true }
thiserror.workspace = true
x509-parser = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
rand_chacha.workspace = true
rand_core.workspace = true
rand_chacha_03 = { package = "rand_chacha", version = "0.3" }
rand_core_06 = { package = "rand_core", version = "0.6" }
rsa = { workspace = true, features = ["pem"] }
sha2.workspace = true
zip.workspace = true

[lints]
workspace = true