[package]
name = "i2pr-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Foundational protocol namespace and error categories for i2pr"
publish = false

[dependencies]
flate2.workspace = true
sha2.workspace = true
zeroize.workspace = true

[dev-dependencies]
i2pr-crypto = { path = "../i2pr-crypto" }
rand_chacha.workspace = true
rand_core.workspace = true

[lints]
workspace = true
