//! Plan 178 IRC client profile configuration and central hard
//! ceilings used across the IRC module.
//!
//! Plan 178 §3 / §3.1 require every length, count, deadline, and
//! generated byte region to have a hard typed ceiling. This module
//! exposes those constants together with the per-service
//! [`IrcClientOptions`] surface the daemon parses from TOML and
//! passes to the runtime-neutral IRC module.
//!
//! ## Ceilings (Plan 178 §3.1)
//!
//! | Region | Default | Hard cap |
//! | --- | ---: | ---: |
//! | Core message (non-tag) | 512 | 512 |
//! | Tag envelope (`@tag …` + leading space) | 8191 | 8191 |
//! | Client-originated tag data | 4094 | 4094 |
//! | Retained per-direction line buffer | 8192 | 8192 |
//! | Generated line bytes | 8192 | 8192 |
//!
//! The total line retention ceiling is the sum of the documented
//! maxima plus terminator allowance so partial reads can sit in the
//! buffer until the terminator arrives.

#![forbid(unsafe_code)]

use std::collections::BTreeSet;

use crate::errors::ServiceTunnelError;

/// Maximum bytes for one IRC core (non-tag) message portion,
/// inclusive of the trailing CRLF. Plan 178 §3.1 documents this as
/// the modern IRC/IRCv3 core line cap.
pub const IRC_CORE_MAX_BYTES: usize = 512;
/// Maximum bytes for the IRCv3 message-tag envelope (leading `@`
/// plus tag keys/values plus the separating space) per line.
pub const IRC_TAG_ENVELOPE_MAX_BYTES: usize = 8191;
/// Maximum bytes of client-originated tag data per line. The
/// envelope ceiling may also be enforced; this is the dedicated
/// cap for tag-value material carried inside the envelope.
pub const IRC_CLIENT_TAG_DATA_MAX_BYTES: usize = 4094;
/// Maximum bytes for the per-direction partial-line buffer
/// (combined tag + core + terminator allowance).
pub const IRC_LINE_BUFFER_MAX_BYTES: usize = 8192;
/// Maximum bytes for one generated line after rewrite/filter.
pub const IRC_GENERATED_LINE_MAX_BYTES: usize = 8192;
/// Maximum number of tags on one message.
pub const IRC_TAG_COUNT_MAX: usize = 128;
/// Maximum bytes for a single tag key.
pub const IRC_TAG_KEY_MAX_BYTES: usize = 64;
/// Maximum number of allowed PRIVMSG/NOTICE parameter slots the
/// filter retains per connection for inbound CTCP accounting.
pub const IRC_CTCP_COUNTER_CEILINGS: usize = 1024;
/// Maximum number of PRIVMSG/NOTICE commands per second the
/// outbound filter will inspect (a soft accounting ceiling, not
/// a flow control point).
pub const IRC_OPTIONS_MAX_ALLOWED_HOSTS: usize = 16;

/// Stable replacement text used when a configured privacy profile
/// rewrites a client-generated application/version string. Plan
/// 178 §6.3 documents the M10 minimum as "pass ordinary reasons
/// unchanged unless the privacy profile is configured to rewrite";
/// this constant is the documented stable replacement when the
/// operator opts in.
pub const DEFAULT_QUIT_REASON: &str = "i2pr";
/// Default replacement hostname emitted for the USER rewrite.
pub const DEFAULT_USER_HOSTNAME: &str = "i2p";
/// Default replacement servername emitted for the USER rewrite.
pub const DEFAULT_USER_SERVERNAME: &str = "localhost";
/// Default replacement PING location argument emitted when a
/// client PING includes a proxy-revealing location.
pub const DEFAULT_PING_LOCATION: &str = "i2p";

/// IRC command classification allowlist categories (Plan 178 §4,
/// extended by Plan 179 §7 for the server-side `SERVER` command).
///
/// Commands are categorized client-originated or server-originated
/// and given a typed [`IrcCommand`] identity. The classifier only
/// classifies; rewriting is layered above.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum IrcCommand {
    Pass,
    Cap,
    Authenticate,
    Nick,
    User,
    /// Server-to-server IRC handshake (Plan 179 §7). Carries a
    /// server name (not a per-user identity) and is not
    /// rewritten; the daemon passes the line through verbatim.
    Server,
    Ping,
    Pong,
    Join,
    Part,
    Quit,
    Privmsg,
    Notice,
    Mode,
    Topic,
    Away,
    Names,
    List,
    Who,
    Whois,
    Whowas,
    Ison,
    Invite,
    Kick,
    Userhost,
    /// Numeric server reply (e.g. `001`, `002`, `372`).
    NumericReply,
    /// One of the documented server-originated commands that is
    /// not a numeric reply.
    ServerCommand,
}

impl IrcCommand {
    /// Returns the canonical upper-case command spelling.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pass => "PASS",
            Self::Cap => "CAP",
            Self::Authenticate => "AUTHENTICATE",
            Self::Nick => "NICK",
            Self::User => "USER",
            Self::Server => "SERVER",
            Self::Ping => "PING",
            Self::Pong => "PONG",
            Self::Join => "JOIN",
            Self::Part => "PART",
            Self::Quit => "QUIT",
            Self::Privmsg => "PRIVMSG",
            Self::Notice => "NOTICE",
            Self::Mode => "MODE",
            Self::Topic => "TOPIC",
            Self::Away => "AWAY",
            Self::Names => "NAMES",
            Self::List => "LIST",
            Self::Who => "WHO",
            Self::Whois => "WHOIS",
            Self::Whowas => "WHOWAS",
            Self::Ison => "ISON",
            Self::Invite => "INVITE",
            Self::Kick => "KICK",
            Self::Userhost => "USERHOST",
            Self::NumericReply | Self::ServerCommand => "",
        }
    }
}

/// Configuration knob for whether the M10 IRC profile rewrites a
/// QUIT/PART reason that contains a proxy-generated version
/// string.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum ReasonRewritePolicy {
    /// Pass ordinary reasons unchanged (Plan 178 §6.3 minimum).
    #[default]
    Keep,
    /// Replace the reason with [`DEFAULT_QUIT_REASON`] when it
    /// contains a documented proxy-generated version marker.
    ReplaceStable,
}

/// M10 IRC client profile options attached to a
/// [`crate::config::ServiceTunnelSpec`] whose `kind` is
/// [`crate::config::ServiceTunnelKind::IrcClient`].
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IrcClientOptions {
    /// Bounded list of static-alias / `.i2p` hostnames the
    /// proxy is configured to allow for the fixed target. The
    /// I2P IRC destination configured on the spec is the actual
    /// streaming peer; this list is an explicit narrowing for the
    /// IRC profile when the operator wants to pin a host alias.
    /// Empty means "any `.i2p` host that the manager can resolve".
    pub allowed_hosts: BTreeSet<String>,
    /// Whether to replace proxy-generated version strings in
    /// QUIT/PART reasons. Defaults to [`ReasonRewritePolicy::Keep`].
    pub reason_rewrite: ReasonRewritePolicy,
    /// Maximum length of a USER realname field after the colon
    /// separator. Names longer than this are rejected as
    /// `BadRequest` rather than truncated into a different
    /// syntactically valid command.
    pub user_realname_max_bytes: usize,
}

impl Default for IrcClientOptions {
    fn default() -> Self {
        Self {
            allowed_hosts: BTreeSet::new(),
            reason_rewrite: ReasonRewritePolicy::Keep,
            user_realname_max_bytes: 256,
        }
    }
}

impl IrcClientOptions {
    /// Returns the Plan 178 default policy.
    pub fn defaults() -> Self {
        Self::default()
    }

    /// Validates the IRC profile options structurally.
    pub fn validate(&self) -> Result<(), ServiceTunnelError> {
        if self.allowed_hosts.len() > IRC_OPTIONS_MAX_ALLOWED_HOSTS {
            return Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "irc allowed hosts exceed the per-tunnel ceiling",
            });
        }
        for host in &self.allowed_hosts {
            if !host.is_empty() && !host.ends_with(".i2p") {
                return Err(ServiceTunnelError::ContradictoryOptions {
                    id: String::new(),
                    reason: "irc allowed hosts must end with .i2p",
                });
            }
        }
        if self.user_realname_max_bytes == 0
            || self.user_realname_max_bytes > IRC_GENERATED_LINE_MAX_BYTES
        {
            return Err(ServiceTunnelError::ContradictoryOptions {
                id: String::new(),
                reason: "irc user_realname_max_bytes out of range",
            });
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_validate() {
        IrcClientOptions::defaults()
            .validate()
            .expect("defaults validate");
    }

    #[test]
    fn reason_rewrite_defaults_to_keep() {
        let options = IrcClientOptions::defaults();
        assert_eq!(options.reason_rewrite, ReasonRewritePolicy::Keep);
    }

    #[test]
    fn non_i2p_allowed_host_rejected() {
        let mut options = IrcClientOptions::defaults();
        options.allowed_hosts.insert("example.com".to_owned());
        assert!(options.validate().is_err());
    }

    #[test]
    fn zero_realname_rejected() {
        let mut options = IrcClientOptions::defaults();
        options.user_realname_max_bytes = 0;
        assert!(options.validate().is_err());
    }

    #[test]
    fn oversized_allowed_host_set_rejected() {
        let mut options = IrcClientOptions::defaults();
        for index in 0..(IRC_OPTIONS_MAX_ALLOWED_HOSTS + 1) {
            options.allowed_hosts.insert(format!("alias-{index}.i2p"));
        }
        assert!(options.validate().is_err());
    }
}
